### Import Libiraries:

In [1]:
#import libiraries for reading data
import pandas as pd
import numpy as np

### Data Visualization:

In [10]:
#Read the data and visualize it:
Data = pd.read_csv('C:Path/Covid Dataset.csv')
Data

,Breathing Problem,Fever,Dry Cough,Sore throat,Running Nose,Asthma,Chronic Lung Disease,Headache,Heart Disease,Diabetes,...,Fatigue,Gastrointestinal,Abroad travel,Contact with COVID Patient,Attended Large Gathering,Visited Public Exposed Places,Family working in Public Exposed Places,Wearing Masks,Sanitization from Market,COVID-19
0,Yes,Yes,Yes,Yes,Yes,No,No,No,No,Yes,...,Yes,Yes,No,Yes,No,Yes,Yes,No,No,Yes
1,Yes,Yes,Yes,Yes,No,Yes,Yes,Yes,No,No,...,Yes,No,No,No,Yes,Yes,No,No,No,Yes
2,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,Yes,...,Yes,Yes,Yes,No,No,No,No,No,No,Yes
3,Yes,Yes,Yes,No,No,Yes,No,No,Yes,Yes,...,No,No,Yes,No,Yes,Yes,No,No,No,Yes
4,Yes,Yes,Yes,Yes,Yes,No,Yes,Yes,Yes,Yes,...,No,Yes,No,Yes,No,Yes,No,No,No,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5429,Yes,Yes,No,Yes,Yes,Yes,Yes,No,No,No,...,Yes,Yes,No,No,No,No,No,No,No,Yes
5430,Yes,Yes,Yes,No,Yes,Yes,No,Yes,No,Yes,...,Yes,No,No,No,No,No,No,No,No,Yes
5431,Yes,Yes,Yes,No,No,No,No,No,Yes,No,...,No,No,No,No,No,No,No,No,No,No
5432,Yes,Yes,Yes,No,Yes,No,No,Yes,Yes,No,...,No,No,No,No,No,No,No,No,No,No
5433,Yes,Yes,Yes,No,Yes,Yes,No,Yes,No,Yes,...,Yes,No,No,No,No,No,No,No,No,No

In [11]:
#check if there is  any column that does not contain binary input (all yes or all no)
for i in Data.columns:
    if len(np.unique(Data[i].values)) != 2:
        print(i)

Wearing Masks
Sanitization from Market

In [12]:
#Remove these columns
Data = Data.drop(['Wearing Masks','Sanitization from Market'], axis=1)

### Data Preprocessing:

In [ ]:
#get the features
Features = Data.drop('COVID-19',axis=1)
Features

,Breathing Problem,Fever,Dry Cough,Sore throat,Running Nose,Asthma,Chronic Lung Disease,Headache,Heart Disease,Diabetes,Hyper Tension,Fatigue,Gastrointestinal,Abroad travel,Contact with COVID Patient,Attended Large Gathering,Visited Public Exposed Places,Family working in Public Exposed Places
0,Yes,Yes,Yes,Yes,Yes,No,No,No,No,Yes,Yes,Yes,Yes,No,Yes,No,Yes,Yes
1,Yes,Yes,Yes,Yes,No,Yes,Yes,Yes,No,No,No,Yes,No,No,No,Yes,Yes,No
2,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,Yes,No,Yes,Yes,Yes,No,No,No,No
3,Yes,Yes,Yes,No,No,Yes,No,No,Yes,Yes,No,No,No,Yes,No,Yes,Yes,No
4,Yes,Yes,Yes,Yes,Yes,No,Yes,Yes,Yes,Yes,Yes,No,Yes,No,Yes,No,Yes,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5429,Yes,Yes,No,Yes,Yes,Yes,Yes,No,No,No,No,Yes,Yes,No,No,No,No,No
5430,Yes,Yes,Yes,No,Yes,Yes,No,Yes,No,Yes,Yes,Yes,No,No,No,No,No,No
5431,Yes,Yes,Yes,No,No,No,No,No,Yes,No,Yes,No,No,No,No,No,No,No
5432,Yes,Yes,Yes,No,Yes,No,No,Yes,Yes,No,No,No,No,No,No,No,No,No
5433,Yes,Yes,Yes,No,Yes,Yes,No,Yes,No,Yes,Yes,Yes,No,No,No,No,No,No

In [ ]:
#Labels
Label = Data['COVID-19']
pd.DataFrame(Label)

     COVID-19
0         Yes
1         Yes
2         Yes
3         Yes
4         Yes
...       ...
5429      Yes
5430      Yes
5431       No
5432       No
5433       No

[5434 rows x 1 columns]

In [ ]:
#Encode data
from sklearn.preprocessing import OrdinalEncoder

# Create encoder
orden = OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1)
Features = orden.fit_transform(Features)

### Train the model:

In [ ]:
#train Test split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(Features, Label, test_size=0.3, random_state=0, stratify=Label)

In [21]:
#choosing the best classifier
from lazypredict.Supervised import LazyClassifier
 
clf = LazyClassifier(verbose=0,ignore_warnings=True,custom_metric=None)
models,predictions = clf.fit(X_train, X_test, y_train, y_test)

print(models)

                             Accuracy  Balanced Accuracy   ROC AUC  F1 Score  \
Model
BaggingClassifier            0.983446           0.984912  0.998246  0.983628
ExtraTreeClassifier          0.983446           0.984912  0.998153  0.983628
DecisionTreeClassifier       0.983446           0.984912  0.998153  0.983628
RandomForestClassifier       0.983446           0.984912  0.998460  0.983628
LabelSpreading               0.983446           0.984912  0.998223  0.983628
LabelPropagation             0.983446           0.984912  0.997874  0.983628
ExtraTreesClassifier         0.983446           0.984912  0.998153  0.983628
SVC                          0.985898           0.981602  0.996396  0.985957
KNeighborsClassifier         0.975475           0.971521  0.997490  0.975731
SGDClassifier                0.981606           0.968077  0.995559  0.981562
AdaBoostClassifier           0.969957           0.958443  0.995447  0.970152
LogisticRegression           0.975475           0.953411  0.995446  0.975293
LinearSVC                    0.971796           0.948717  0.995298  0.971622
CalibratedClassifierCV       0.971796           0.948717  0.995296  0.971622
BernoulliNB                  0.968118           0.946437  0.992688  0.968040
NearestCentroid              0.938688           0.945103  0.984139  0.940970
LinearDiscriminantAnalysis   0.965665           0.934051  0.986344  0.965277
RidgeClassifier              0.967505           0.931569  0.986344  0.966942
RidgeClassifierCV            0.967505           0.931569  0.986361  0.966942
PassiveAggressiveClassifier  0.955242           0.927592  0.991313  0.955215
Perceptron                   0.952177           0.925692  0.986756  0.952291
GaussianNB                   0.793378           0.871960  0.993340  0.814212
DummyClassifier              0.806867           0.500000  0.500000  0.720622

                             Precision    Recall  Time Taken
Model
BaggingClassifier             0.984212  0.983446    0.092837
ExtraTreeClassifier           0.984212  0.983446    0.041134
DecisionTreeClassifier        0.984212  0.983446    0.043779
RandomForestClassifier        0.984212  0.983446    0.257510
LabelSpreading                0.984212  0.983446    1.261307
LabelPropagation              0.984212  0.983446    0.979708
ExtraTreesClassifier          0.984212  0.983446    0.257339
SVC                           0.986072  0.985898    0.175137
KNeighborsClassifier          0.976343  0.975475    3.667063
SGDClassifier                 0.981535  0.981606    0.050246
AdaBoostClassifier            0.970480  0.969957    0.308037
LogisticRegression            0.975279  0.975475    0.046592
LinearSVC                     0.971564  0.971796    0.044744
CalibratedClassifierCV        0.971564  0.971796    0.134356
BernoulliNB                   0.967980  0.968118    0.050000
NearestCentroid               0.948001  0.938688    0.039500
LinearDiscriminantAnalysis    0.965265  0.965665    0.061663
RidgeClassifier               0.967250  0.967505    0.043765
RidgeClassifierCV             0.967250  0.967505    0.048138
PassiveAggressiveClassifier   0.955189  0.955242    0.039378
Perceptron                    0.952423  0.952177    0.043067
GaussianNB                    0.900175  0.793378    0.042398
DummyClassifier               0.651034  0.806867    0.039648

In [23]:
#We choose the best mosel according to the accuracy and the time taken (Decision tree)
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier()

#Train the model using the training sets
model.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = model.predict(X_test)

In [35]:
X_test.shape

(1631, 18)

In [36]:
X_train.values[0]

array([1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1])

In [25]:
from sklearn.metrics import classification_report, confusion_matrix

conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

#Print
print("Confusion Matrix:\n", conf_matrix)
print("\n Classification report of the model: \n",classification_report(y_test, y_pred))

Confusion Matrix:
 [[ 311    4]
 [  23 1293]]

 Classification report of the model:
               precision    recall  f1-score   support

          No       0.93      0.99      0.96       315
         Yes       1.00      0.98      0.99      1316

    accuracy                           0.98      1631
   macro avg       0.96      0.98      0.97      1631
weighted avg       0.98      0.98      0.98      1631

### Natural Language Processing Model for the Chatbot:

In [28]:
import nltk
from nltk.stem import WordNetLemmatizer
from nltk.stem.porter import PorterStemmer

#Natural language processing
nltk.download('popular',quiet=True)
stemmer = PorterStemmer()

def tokenize(sentence):
    return nltk.word_tokenize(sentence)


def stem(word):
    return stemmer.stem(word)

def bag_of_words(tokenized_sentence, words):
    # stem each word
    sentence_words = [stem(word) for word in tokenized_sentence]
    # initialize bag with 0 for each word
    bag = np.zeros(len(words), dtype=np.float32)
    for idx, w in enumerate(words):
        if w in sentence_words: 
            bag[idx] = 1

    return bag

In [29]:
stem("yes")

'ye'

### ChatBot preparation:

In [ ]:
# Questions of ChatBot
lit = [ "\nBot: According to your answers, your Covid test's result is: ",
         "\nBot: Is there anyone from your family members who is working in Public Exposed Places ?\n",
         "\nBot: Did you Visit a Public Exposed Places ?\n",
         "\nBot: Did you attende a large gathering ?\n",
         "\nBot: Is there anyone you know has Covid ?\n",
         "\nBot: Did you travel abroad these last 15 days ?\n",
         "\nBot: Do you have problem in your Gastrointestinal ?\n",
         "\nBot: Do you feel Fatigue ?\n",
         "\nBot: Are you HyperTension ?\n",
         "\nBot: Are you Diabetic?\n",
         "\nBot: Do you have Heart Disease ?\n",
         "\nBot: What about having a Headache ?\n",
         "\nBot: Do you have Chronic Lung Disease ?\n",
         "\nBot:  Do you have Asthma ?\n",
         "\nBot:  What about running nose ?\n",
         "\nBot:  Do you have Sore throat?\n",
         "\nBot: Do you Cough dry coughs?\n",
         "\nBot: Do you have fever?\n"
         ]
len(lit)

18

### Application creation

In [ ]:
import tkinter as tk
from tkinter import *

llist = lit.copy()
# Global Variables
BG_GRAY = "#ABB2B9"
BG_COLOR = "#17202A"
TEXT_COLOR = "#EAECEE"

FONT = "Helvetica 14"
FONT_BOLD = "Helvetica 13 bold"

words = ["ye","no"]
diag = []

# Main Functions
def send_answer(diag):
    
    inp = questionField.get()
    textarea.insert(END,"You: "+ inp +'\n')
    i = llist.pop()
    textarea.insert(END,i)
    questionField.delete(0,END)
    
    X = bag_of_words(tokenize(inp),words)   
    if(X[0] == 1):
        diag.append(1)
    else:
        diag.append(0)
        
    if llist == []:

        if(model.predict(pd.DataFrame(diag).T) == 1):
            textarea.insert(END,"'Positve', you must visite the closest hospital ASAP. Thank you and have a nice day")
        else:
            textarea.insert(END,"'Negative', stay safe and wear your Mask. Thank you and have a nice day ^-^")
        
        print('Program is finished')

def click(event):
    askButton.invoke()
    
#-----------------------------------------------------------------------------------------------------   
#root= tk.Toplevel()
root = Tk()

root.geometry('500x570+100+30')
root.title('CoviBot')
root.config(bg=BG_COLOR)

'''# head label (picture)
logoPic = PhotoImage(file = 'Path/chatbot.jpg').subsample(5)

logoPicLabel=tk.Label(root,image=logoPic,bg=BG_COLOR)
logoPicLabel.pack(pady=5)'''

# frame widget
centerFrame = Frame(root)
centerFrame.pack()

# Scroll bar
scrollbar = Scrollbar(centerFrame)
scrollbar.place(relheight = 1, relx = 0.974)
scrollbar.pack(side = RIGHT)

# Text widget
textarea = Text(centerFrame,font=('Helvetica',11, 'bold'),height=18,yscrollcommand=scrollbar.set ,wrap='word')
textarea.pack(side = LEFT)

# configure scroll bar
scrollbar.config(command= textarea.yview)

# message entry box
questionField=Entry(root,font=('Helvetica',11))
questionField.pack(pady=15,fill=X)

textarea.insert(END,"Bot: Hi,I'm CoviBot,your assistant. How do you feel today? Do you have any breathing problems?\n")

# send button
askButton=Button(root,text ="Send", command= lambda: send_answer(diag))
askButton.pack()

root.bind('<Return>',click)

root.mainloop()